### ISSUE TITLE
Will the demo be updated to the newest versions?

### ISSUE THREAD

**Issue by sebfia** [aurelia-ui-toolkits/demo-syncfusion#2]
First of all - thank you for the syncfusion-bridge!
Will the demo be updated to the newest versions of aurelia-syncfusion-bridge (0.4.0) and babel?

**Comment by karthickthangasamy** [comment]
@sebfia Yes, we will update the demo.

**Comment by karthickthangasamy** [comment]
demo updated with `aurelia-syncfusion-bridge@0.5.0`
